[pytest]
addopts = -n auto --strict-markers --strict-config --verbose
# check for pytest_xdist_auto_num_workers() for maximum cores allowed during testing
testpaths = tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
