[pytest]
addopts = -n 6 --strict-markers
# comment out for single process testing, -n 8 for multi-process testing with 8 processes
testpaths = tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
